### ISSUE TITLE
outdated pydep/pip fails to parse pip 6.0 requirements.txt syntax

### ISSUE THREAD

**Issue by jayvdb** [sourcegraph/sourcegraph.com#412]
`pydep-run.py` fails if requirements.txt uses features introduced by pip 6.0

e.g. https://sourcegraph.com/github.com/jayvdb/pywikibot-core/.builds/9745542476f8d2fa7d84a262362060e8a7a07ffa/1/log
```
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690: Traceback (most recent call last):   File "/venv/bin/pydep-run.py", line 132, in <module> 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     main()   File "/venv/bin/pydep-run.py", line 36, in main     args.func(args)   File "/venv/bin/pydep-run.py", line 66, in dep     reqs, err = pydep.req.requirements(args.dir, not args.raw)   File "/venv/local/lib/python2.7/site-packages/pydep/req.py", line 23, in requirements 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     reqs, err = requirements_from_requirements_txt(rootdir)   File "/venv/local/lib/python2.7/site-packages/pydep/req.py", line 62, in requirements_from_requirements_txt 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     for install_req in pip.req.parse_requirements(f):   File "/venv/local/lib/python2.7/site-packages/pip/req.py", line 1631, in parse_requirements 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))   File "/venv/local/lib/python2.7/site-packages/pip/req.py", line 172, in from_line 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     return cls(req, comes_from, url=url, prereleases=prereleases)   File "/venv/local/lib/python2.7/site-packages/pip/req.py", line 70, in __init__ 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     req = pkg_resources.Requirement.parse(req)   File "/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     reqs = list(parse_requirements(s))   File "/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")   File "/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2583, in scan_list 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690:     "Expected ',' or end-of-list in",line,"at",line[p:] ValueError:  
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690: ("Expected ',' or end-of-list in", "cryptography<=0.8.2 ; python_version < '2.7'", 'at', " ; python_version < '2.7'") 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690: exit status 1 
2015-08-06 18:57:07 -0700 -0700 ip-172-22-2-64 8e3d25caf690: failed to scan for source units: scanner [docker run --memory=4g -i --volume=/tmp/sg/builds/github.com/jayvdb/pywikibot-core:/src:ro sourcegraph.com-sourcegraph-srclib-python scan]: EOF 
```

https://github.com/sourcegraph/pydep says it supports pip 7.0+, so maybe the latest pydep isnt used yet.

**Comment by jayvdb** [comment]
This problem is not appearing in a new build.
